### ISSUE TITLE
Create a PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by tempoColl** [tempoCollaboration/TimeEvolvingMPO#1]
We should probably have a PULL_REQUEST_TEMPLATE.md that contains a checklist for a pull request that is ready to merge. Should look something like this:
...
- [ ] added / changed meaningful doc strings to new code (if any)
- [ ] added / changed documentation (if neccessary)
- [ ] added test for the new functionality (if any)
- [ ] tests are all successful locally
....

**Comment by alex-konovalov** [comment]
Good idea, we have one at https://github.com/gap-system/gap/blob/master/.github/pull_request_template.md for GAP. However, I think it's mostly a check list for code review, rather than for a submitter. Regular contributors tend to ignore it. Byt still, better to have it, and let people delete it instantly, than not to have it...

**Comment by gefux** [comment]
Thank you Alexander! I agree.
Now that the public repository awoke from its deep slumber, we also have a pull request template.

**Comment by alex-konovalov** [comment]
@gefux thanks, does it work? I think it should be in the `.github` subdirectory, to be automatically inserted into a PR description...
