### ISSUE TITLE
The correlation function of discrete bath modes doesn't decay quickly. Can I use TEMPO in this case?

### ISSUE THREAD

**Issue by Mulliken** [tempoCollaboration/TimeEvolvingMPO#19]
Hi TEMPO developers,

I was wondering if I could use TEMPO to simulate a system consisting of a spin and a set of discrete modes. After plotting the correlation function of the discrete modes, I found the function doesn't decay. Instead, it oscillates rapidly. An extreme case is a single mode, whose correlation function is nearly a periodic function. Would is be possible to use TEMPO, given that the correlation function doesn't decay?

Best,
Mulliken

**Comment by gefux** [comment]
Hi Mulliken,

I believe in principle you can, however, I'd estimate that finding the right convergence parameters might be quite tricky.  The fact that the correlation function doesn't decay means that the `dkmax` parameter must always  be larger or equal than the number of timesteps you are interested in. Choosing a good `dt` will probably depend quite a lot on the modes you add in.

I'd say that in the case of discrete bath modes the ACE method would in fact fit much better: 
Here the paper: arxiv.org/abs/2101.01653 
Here the code: https://github.com/mcygorek/ACE

ACE is another method to create a process tensor for a quite large class of different environments. The process tensor can then be used to extract the system dynamics, multi-time correlations, etc. A lot of the other functionality that we are currently developing for this package is therefore compatible with ACE and we are therefore also working on an common file format to store process tensors to link ACE with this package.

If you'd like to give it a go with TEMPO anyway, maybe we could try help you a bit with that if you give some details of a concrete example you'd be interested in.

Best, gefux

**Comment by Mulliken** [comment]
Hi gefux,

Thank you so much!! I think it will be greatly helpful if you could look into the model I tried to simulate. The parameters and the python script were organized in a [repository](https://github.com/Mulliken/Three-State-Model.git). The main file is `tempo_discrete.py` and the parameters for the discrete modes are stored in `bath_para.py`. In the main file, I wrote a function to generate the correlation function of the discrete modes, in addition to the standard tempo code.

Best,
Mulliken

**Comment by gefux** [comment]
Hi - no problem. I'll get back to you sometime this week when I had a chance to have a closer look at your script / tried a few convergence parameters.
Best, gefux

**Comment by Mulliken** [comment]
Thank you!!

Best,
Mulliken

**Comment by gefux** [comment]
Hi Mulliken,

I apologise for the slightly delayed response. I've now had a closer look at the example in your [script](https://github.com/Mulliken/Three-State-Model)  (commit 21113c9). I am afraid I don't have much to add to my first response yet.

The problem is that, as it is set up currently, you try to simulate a three level quantum system strongly coupled to an environment with a rapidly oscillating correlation function. Over the time interval of 0.19 the environment mode at 1384.4  oscillates 0.19 * 1384.4 / (2pi) ~= 42 times. This makes it numerically quite challenging when approaching it with TEMPO. The strong suit of TEMPO is that it can deal very well with a continuous set of strongly coupled modes, which cannot be modelled with a few discrete modes --- i.e. the opposite of your example. 

Having said that: if you are really only interested in the influence of this single environment mode, I'd rather simply consider the three level + the single environment mode as the closed system and simulate / diagonalise this. If you want to include several discrete environment modes, I still think ACE would be the best choice.

I'll come back to your example sometimes in the next weeks and keep you posted if in case I have anything more to share.

**Comment by Mulliken** [comment]
Hi gefux,

Thanks for the reply! I also tried some combinations of convergence parameters but only got the short-time (a tenth of what's desired) dynamics seemingly correct. I also tried ASE but the problem is that I couldn't use a too large cutoff for the number of states of each bath mode, which however is seemingly necessary to obtain converged results. 

You provided a good insight that I should probably only be focused on the exact dynamics of system+the single mode. Thanks!!

Best,
Mulliken
